import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/sections/header";

import "sweetalert2/dist/sweetalert2.js";
import { AuthProvider } from "./context/AuthContext";
import ReduxStateProvider from "./Redux/ContextProvider/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <AuthProvider>
          <ReduxStateProvider>
            {" "}
            <NavBar />
            {children}
          </ReduxStateProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
