import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/sections/header";
import InitProvider from "./Redux/ContextProvider/initialProvider";
import "sweetalert2/dist/sweetalert2.js";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <InitProvider>
          {" "}
          <NavBar />
          {children}
        </InitProvider>
      </body>
    </html>
  );
}
