import mongoose from "mongoose";
import connectToMongo from "../lib/mongoConnection";
import Book from "./book.model";
import "dotenv/config";
const books = [
    {
      title: "The Alchemist",
      description: "A novel by Brazilian author Paulo Coelho that became an international bestseller.",
      coverImage: "/assets/books/book-1.png",
      author: "Paulo Coelho",
      rating: "4.7",
      pages: "208",
      release: "1988",
      genre: ["Adventure", "Fantasy"],
      oldPrice: "20",
      newPrice: "15",
    },
    {
      title: "To Kill a Mockingbird",
      description: "A Pulitzer Prize-winning novel about racial injustice in the American South.",
      coverImage: "/assets/books/book-2.png",
      author: "Harper Lee",
      rating: "4.8",
      pages: "281",
      release: "1960",
      genre: ["Fiction", "Classic"],
      oldPrice: "25",
      newPrice: "18",
    },
    {
      title: "1984",
      description: "A dystopian novel about totalitarian surveillance and control.",
      coverImage: "/assets/books/book-3.png",
      author: "George Orwell",
      rating: "4.6",
      pages: "328",
      release: "1949",
      genre: ["Dystopian", "Political Fiction"],
      oldPrice: "22",
      newPrice: "17",
    },
    {
      title: "Pride and Prejudice",
      description: "A classic romance novel about love and social status.",
      coverImage: "/assets/books/book-4.png",
      author: "Jane Austen",
      rating: "4.7",
      pages: "279",
      release: "1813",
      genre: ["Romance", "Classic"],
      oldPrice: "20",
      newPrice: "14",
    },
    {
      title: "The Great Gatsby",
      description: "A novel exploring the American Dream and high society in the 1920s.",
      coverImage: "/assets/books/book-5.png",
      author: "F. Scott Fitzgerald",
      rating: "4.5",
      pages: "180",
      release: "1925",
      genre: ["Tragedy", "Fiction"],
      oldPrice: "18",
      newPrice: "13",
    },
    {
      title: "Moby-Dick",
      description: "A tale of obsession and revenge between a whaling captain and a great white whale.",
      coverImage: "/assets/books/book-6.png",
      author: "Herman Melville",
      rating: "4.3",
      pages: "585",
      release: "1851",
      genre: ["Adventure", "Classic"],
      oldPrice: "28",
      newPrice: "20",
    },
    {
      title: "Crime and Punishment",
      description: "A psychological novel about morality and redemption.",
      coverImage: "/assets/books/book-7.png",
      author: "Fyodor Dostoevsky",
      rating: "4.7",
      pages: "671",
      release: "1866",
      genre: ["Philosophical Fiction", "Classic"],
      oldPrice: "30",
      newPrice: "22",
    },
    {
      title: "The Catcher in the Rye",
      description: "A coming-of-age story about teenage rebellion and alienation.",
      coverImage: "/assets/books/book-8.png",
      author: "J.D. Salinger",
      rating: "4.4",
      pages: "277",
      release: "1951",
      genre: ["Fiction", "Classic"],
      oldPrice: "19",
      newPrice: "14",
    },
    {
      title: "The Lord of the Rings",
      description: "An epic fantasy novel about the battle between good and evil.",
      coverImage: "/assets/books/book-9.png",
      author: "J.R.R. Tolkien",
      rating: "4.9",
      pages: "1178",
      release: "1954",
      genre: ["Fantasy", "Adventure"],
      oldPrice: "35",
      newPrice: "25",
    },
    {
      title: "Brave New World",
      description: "A dystopian novel about a futuristic society controlled by pleasure and conformity.",
      coverImage: "/assets/books/book-10.png",
      author: "Aldous Huxley",
      rating: "4.5",
      pages: "311",
      release: "1932",
      genre: ["Dystopian", "Science Fiction"],
      oldPrice: "24",
      newPrice: "18",
    },
    {
      title: "The Hobbit",
      description: "A fantasy adventure novel that sets the stage for The Lord of the Rings.",
      coverImage: "/assets/books/book-11.png",
      author: "J.R.R. Tolkien",
      rating: "4.8",
      pages: "310",
      release: "1937",
      genre: ["Fantasy", "Adventure"],
      oldPrice: "22",
      newPrice: "16",
    },
    {
      title: "Anna Karenina",
      description: "A novel exploring love, passion, and societal constraints in Russia.",
      coverImage: "/assets/books/book-12.png",
      author: "Leo Tolstoy",
      rating: "4.6",
      pages: "864",
      release: "1878",
      genre: ["Romance", "Classic"],
      oldPrice: "27",
      newPrice: "19",
    },
    {
      title: "The Picture of Dorian Gray",
      description: "A novel about beauty, morality, and the cost of eternal youth.",
      coverImage: "/assets/books/book-13.png",
      author: "Oscar Wilde",
      rating: "4.4",
      pages: "254",
      release: "1890",
      genre: ["Gothic Fiction", "Classic"],
      oldPrice: "18",
      newPrice: "13",
    },
    {
      title: "Dracula",
      description: "A classic horror novel that introduced the legend of Count Dracula.",
      coverImage: "/assets/books/book-14.png",
      author: "Bram Stoker",
      rating: "4.5",
      pages: "418",
      release: "1897",
      genre: ["Horror", "Gothic Fiction"],
      oldPrice: "21",
      newPrice: "15",
    },
    {
      title: "Fahrenheit 451",
      description: "A dystopian novel about a future where books are outlawed and burned.",
      coverImage: "/assets/books/book-15.png",
      author: "Ray Bradbury",
      rating: "4.6",
      pages: "256",
      release: "1953",
      genre: ["Dystopian", "Science Fiction"],
      oldPrice: "20",
      newPrice: "14",
    },
    {
      title: "Wuthering Heights",
      description: "A classic gothic romance novel about love and revenge.",
      coverImage: "/assets/books/book-16.png",
      author: "Emily Brontë",
      rating: "4.3",
      pages: "416",
      release: "1847",
      genre: ["Gothic Fiction", "Romance"],
      oldPrice: "22",
      newPrice: "16",
    },
    {
      title: "Frankenstein",
      description: "A gothic novel about the consequences of playing God.",
      coverImage: "/assets/books/book-17.png",
      author: "Mary Shelley",
      rating: "4.4",
      pages: "280",
      release: "1818",
      genre: ["Horror", "Gothic Fiction"],
      oldPrice: "19",
      newPrice: "13",
    },
    {
      title: "The Odyssey",
      description: "An epic poem following the journey of Odysseus returning home.",
      coverImage: "/assets/books/book-18.png",
      author: "Homer",
      rating: "4.7",
      pages: "541",
      release: "8th century BC",
      genre: ["Epic", "Adventure"],
      oldPrice: "29",
      newPrice: "21",
    },
  ];
  
  



  const seedBooks = async () => {
    try {
      await connectToMongo();
      await Book.deleteMany();
   await Book.insertMany(books);
      console.log("Books Seeded Successfully!");
      process.exit(); // Exit process after seeding
    } catch (error) {
      console.error("Error Seeding Books:", error);
      process.exit(1);
    }
  };
  
  seedBooks();
